queue_rules:
  - name: default
    conditions:
      - "#approved-reviews-by>=1"
      - base=master
      - label=automerge

pull_request_rules:
  - name: automerge to main with label automerge and branch protection passing
    conditions:
      - "#approved-reviews-by>=1"
      - base=main
      - label=automerge
    actions:
      queue:
        name: default
        method: squash
        commit_message_template: |
          {{ title }} (#{{ number }})
          {{ body }}
  - name: backport patches to release/v0.9.x branch
    conditions:
      - base=main
      - label=backport:v0.9.x
    actions:
      backport:
        branches:
          - release/v0.9.x  
  - name: backport patches to release/v0.10.x branch
    conditions:
      - base=main
      - label=backport:v0.10.x
    actions:
      backport:
        branches:
          - release/v0.10.x
  - name: backport patches to release/v0.11.x branch
    conditions:
      - base=main
      - label=backport:v0.11.x
    actions:
      backport:
        branches:
          - release/v0.11.x  