// This file is generated by rust-protobuf 2.8.0. Do not edit
// @generated

// https://github.com/Manishearth/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![cfg_attr(rustfmt, rustfmt_skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unsafe_code)]
#![allow(unused_imports)]
#![allow(unused_results)]
//! Generated file from `proofs.proto`

use protobuf::Message as Message_imported_for_functions;
use protobuf::ProtobufEnum as ProtobufEnum_imported_for_functions;

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_2_8_0;

#[derive(PartialEq,Clone,Default)]
pub struct ExistenceProof {
    // message fields
    pub key: ::std::vec::Vec<u8>,
    pub value: ::std::vec::Vec<u8>,
    pub leaf: ::protobuf::SingularPtrField<LeafOp>,
    pub path: ::protobuf::RepeatedField<InnerOp>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a ExistenceProof {
    fn default() -> &'a ExistenceProof {
        <ExistenceProof as ::protobuf::Message>::default_instance()
    }
}

impl ExistenceProof {
    pub fn new() -> ExistenceProof {
        ::std::default::Default::default()
    }

    // bytes key = 1;


    pub fn get_key(&self) -> &[u8] {
        &self.key
    }
    pub fn clear_key(&mut self) {
        self.key.clear();
    }

    // Param is passed by value, moved
    pub fn set_key(&mut self, v: ::std::vec::Vec<u8>) {
        self.key = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_key(&mut self) -> &mut ::std::vec::Vec<u8> {
        &mut self.key
    }

    // Take field
    pub fn take_key(&mut self) -> ::std::vec::Vec<u8> {
        ::std::mem::replace(&mut self.key, ::std::vec::Vec::new())
    }

    // bytes value = 2;


    pub fn get_value(&self) -> &[u8] {
        &self.value
    }
    pub fn clear_value(&mut self) {
        self.value.clear();
    }

    // Param is passed by value, moved
    pub fn set_value(&mut self, v: ::std::vec::Vec<u8>) {
        self.value = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_value(&mut self) -> &mut ::std::vec::Vec<u8> {
        &mut self.value
    }

    // Take field
    pub fn take_value(&mut self) -> ::std::vec::Vec<u8> {
        ::std::mem::replace(&mut self.value, ::std::vec::Vec::new())
    }

    // .proofs.LeafOp leaf = 3;


    pub fn get_leaf(&self) -> &LeafOp {
        self.leaf.as_ref().unwrap_or_else(|| LeafOp::default_instance())
    }
    pub fn clear_leaf(&mut self) {
        self.leaf.clear();
    }

    pub fn has_leaf(&self) -> bool {
        self.leaf.is_some()
    }

    // Param is passed by value, moved
    pub fn set_leaf(&mut self, v: LeafOp) {
        self.leaf = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_leaf(&mut self) -> &mut LeafOp {
        if self.leaf.is_none() {
            self.leaf.set_default();
        }
        self.leaf.as_mut().unwrap()
    }

    // Take field
    pub fn take_leaf(&mut self) -> LeafOp {
        self.leaf.take().unwrap_or_else(|| LeafOp::new())
    }

    // repeated .proofs.InnerOp path = 4;


    pub fn get_path(&self) -> &[InnerOp] {
        &self.path
    }
    pub fn clear_path(&mut self) {
        self.path.clear();
    }

    // Param is passed by value, moved
    pub fn set_path(&mut self, v: ::protobuf::RepeatedField<InnerOp>) {
        self.path = v;
    }

    // Mutable pointer to the field.
    pub fn mut_path(&mut self) -> &mut ::protobuf::RepeatedField<InnerOp> {
        &mut self.path
    }

    // Take field
    pub fn take_path(&mut self) -> ::protobuf::RepeatedField<InnerOp> {
        ::std::mem::replace(&mut self.path, ::protobuf::RepeatedField::new())
    }
}

impl ::protobuf::Message for ExistenceProof {
    fn is_initialized(&self) -> bool {
        for v in &self.leaf {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.path {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_bytes_into(wire_type, is, &mut self.key)?;
                },
                2 => {
                    ::protobuf::rt::read_singular_proto3_bytes_into(wire_type, is, &mut self.value)?;
                },
                3 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.leaf)?;
                },
                4 => {
                    ::protobuf::rt::read_repeated_message_into(wire_type, is, &mut self.path)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.key.is_empty() {
            my_size += ::protobuf::rt::bytes_size(1, &self.key);
        }
        if !self.value.is_empty() {
            my_size += ::protobuf::rt::bytes_size(2, &self.value);
        }
        if let Some(ref v) = self.leaf.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        for value in &self.path {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if !self.key.is_empty() {
            os.write_bytes(1, &self.key)?;
        }
        if !self.value.is_empty() {
            os.write_bytes(2, &self.value)?;
        }
        if let Some(ref v) = self.leaf.as_ref() {
            os.write_tag(3, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        for v in &self.path {
            os.write_tag(4, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        };
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> ExistenceProof {
        ExistenceProof::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeBytes>(
                    "key",
                    |m: &ExistenceProof| { &m.key },
                    |m: &mut ExistenceProof| { &mut m.key },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeBytes>(
                    "value",
                    |m: &ExistenceProof| { &m.value },
                    |m: &mut ExistenceProof| { &mut m.value },
                ));
                fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<LeafOp>>(
                    "leaf",
                    |m: &ExistenceProof| { &m.leaf },
                    |m: &mut ExistenceProof| { &mut m.leaf },
                ));
                fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<InnerOp>>(
                    "path",
                    |m: &ExistenceProof| { &m.path },
                    |m: &mut ExistenceProof| { &mut m.path },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<ExistenceProof>(
                    "ExistenceProof",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static ExistenceProof {
        static mut instance: ::protobuf::lazy::Lazy<ExistenceProof> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ExistenceProof,
        };
        unsafe {
            instance.get(ExistenceProof::new)
        }
    }
}

impl ::protobuf::Clear for ExistenceProof {
    fn clear(&mut self) {
        self.key.clear();
        self.value.clear();
        self.leaf.clear();
        self.path.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for ExistenceProof {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ExistenceProof {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct LeafOp {
    // message fields
    pub hash: HashOp,
    pub prehash_key: HashOp,
    pub prehash_value: HashOp,
    pub length: LengthOp,
    pub prefix: ::std::vec::Vec<u8>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a LeafOp {
    fn default() -> &'a LeafOp {
        <LeafOp as ::protobuf::Message>::default_instance()
    }
}

impl LeafOp {
    pub fn new() -> LeafOp {
        ::std::default::Default::default()
    }

    // .proofs.HashOp hash = 1;


    pub fn get_hash(&self) -> HashOp {
        self.hash
    }
    pub fn clear_hash(&mut self) {
        self.hash = HashOp::NO_HASH;
    }

    // Param is passed by value, moved
    pub fn set_hash(&mut self, v: HashOp) {
        self.hash = v;
    }

    // .proofs.HashOp prehash_key = 2;


    pub fn get_prehash_key(&self) -> HashOp {
        self.prehash_key
    }
    pub fn clear_prehash_key(&mut self) {
        self.prehash_key = HashOp::NO_HASH;
    }

    // Param is passed by value, moved
    pub fn set_prehash_key(&mut self, v: HashOp) {
        self.prehash_key = v;
    }

    // .proofs.HashOp prehash_value = 3;


    pub fn get_prehash_value(&self) -> HashOp {
        self.prehash_value
    }
    pub fn clear_prehash_value(&mut self) {
        self.prehash_value = HashOp::NO_HASH;
    }

    // Param is passed by value, moved
    pub fn set_prehash_value(&mut self, v: HashOp) {
        self.prehash_value = v;
    }

    // .proofs.LengthOp length = 4;


    pub fn get_length(&self) -> LengthOp {
        self.length
    }
    pub fn clear_length(&mut self) {
        self.length = LengthOp::NO_PREFIX;
    }

    // Param is passed by value, moved
    pub fn set_length(&mut self, v: LengthOp) {
        self.length = v;
    }

    // bytes prefix = 5;


    pub fn get_prefix(&self) -> &[u8] {
        &self.prefix
    }
    pub fn clear_prefix(&mut self) {
        self.prefix.clear();
    }

    // Param is passed by value, moved
    pub fn set_prefix(&mut self, v: ::std::vec::Vec<u8>) {
        self.prefix = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_prefix(&mut self) -> &mut ::std::vec::Vec<u8> {
        &mut self.prefix
    }

    // Take field
    pub fn take_prefix(&mut self) -> ::std::vec::Vec<u8> {
        ::std::mem::replace(&mut self.prefix, ::std::vec::Vec::new())
    }
}

impl ::protobuf::Message for LeafOp {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_proto3_enum_with_unknown_fields_into(wire_type, is, &mut self.hash, 1, &mut self.unknown_fields)?
                },
                2 => {
                    ::protobuf::rt::read_proto3_enum_with_unknown_fields_into(wire_type, is, &mut self.prehash_key, 2, &mut self.unknown_fields)?
                },
                3 => {
                    ::protobuf::rt::read_proto3_enum_with_unknown_fields_into(wire_type, is, &mut self.prehash_value, 3, &mut self.unknown_fields)?
                },
                4 => {
                    ::protobuf::rt::read_proto3_enum_with_unknown_fields_into(wire_type, is, &mut self.length, 4, &mut self.unknown_fields)?
                },
                5 => {
                    ::protobuf::rt::read_singular_proto3_bytes_into(wire_type, is, &mut self.prefix)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if self.hash != HashOp::NO_HASH {
            my_size += ::protobuf::rt::enum_size(1, self.hash);
        }
        if self.prehash_key != HashOp::NO_HASH {
            my_size += ::protobuf::rt::enum_size(2, self.prehash_key);
        }
        if self.prehash_value != HashOp::NO_HASH {
            my_size += ::protobuf::rt::enum_size(3, self.prehash_value);
        }
        if self.length != LengthOp::NO_PREFIX {
            my_size += ::protobuf::rt::enum_size(4, self.length);
        }
        if !self.prefix.is_empty() {
            my_size += ::protobuf::rt::bytes_size(5, &self.prefix);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if self.hash != HashOp::NO_HASH {
            os.write_enum(1, self.hash.value())?;
        }
        if self.prehash_key != HashOp::NO_HASH {
            os.write_enum(2, self.prehash_key.value())?;
        }
        if self.prehash_value != HashOp::NO_HASH {
            os.write_enum(3, self.prehash_value.value())?;
        }
        if self.length != LengthOp::NO_PREFIX {
            os.write_enum(4, self.length.value())?;
        }
        if !self.prefix.is_empty() {
            os.write_bytes(5, &self.prefix)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> LeafOp {
        LeafOp::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeEnum<HashOp>>(
                    "hash",
                    |m: &LeafOp| { &m.hash },
                    |m: &mut LeafOp| { &mut m.hash },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeEnum<HashOp>>(
                    "prehash_key",
                    |m: &LeafOp| { &m.prehash_key },
                    |m: &mut LeafOp| { &mut m.prehash_key },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeEnum<HashOp>>(
                    "prehash_value",
                    |m: &LeafOp| { &m.prehash_value },
                    |m: &mut LeafOp| { &mut m.prehash_value },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeEnum<LengthOp>>(
                    "length",
                    |m: &LeafOp| { &m.length },
                    |m: &mut LeafOp| { &mut m.length },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeBytes>(
                    "prefix",
                    |m: &LeafOp| { &m.prefix },
                    |m: &mut LeafOp| { &mut m.prefix },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<LeafOp>(
                    "LeafOp",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static LeafOp {
        static mut instance: ::protobuf::lazy::Lazy<LeafOp> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const LeafOp,
        };
        unsafe {
            instance.get(LeafOp::new)
        }
    }
}

impl ::protobuf::Clear for LeafOp {
    fn clear(&mut self) {
        self.hash = HashOp::NO_HASH;
        self.prehash_key = HashOp::NO_HASH;
        self.prehash_value = HashOp::NO_HASH;
        self.length = LengthOp::NO_PREFIX;
        self.prefix.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for LeafOp {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for LeafOp {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct InnerOp {
    // message fields
    pub hash: HashOp,
    pub prefix: ::std::vec::Vec<u8>,
    pub suffix: ::std::vec::Vec<u8>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a InnerOp {
    fn default() -> &'a InnerOp {
        <InnerOp as ::protobuf::Message>::default_instance()
    }
}

impl InnerOp {
    pub fn new() -> InnerOp {
        ::std::default::Default::default()
    }

    // .proofs.HashOp hash = 1;


    pub fn get_hash(&self) -> HashOp {
        self.hash
    }
    pub fn clear_hash(&mut self) {
        self.hash = HashOp::NO_HASH;
    }

    // Param is passed by value, moved
    pub fn set_hash(&mut self, v: HashOp) {
        self.hash = v;
    }

    // bytes prefix = 2;


    pub fn get_prefix(&self) -> &[u8] {
        &self.prefix
    }
    pub fn clear_prefix(&mut self) {
        self.prefix.clear();
    }

    // Param is passed by value, moved
    pub fn set_prefix(&mut self, v: ::std::vec::Vec<u8>) {
        self.prefix = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_prefix(&mut self) -> &mut ::std::vec::Vec<u8> {
        &mut self.prefix
    }

    // Take field
    pub fn take_prefix(&mut self) -> ::std::vec::Vec<u8> {
        ::std::mem::replace(&mut self.prefix, ::std::vec::Vec::new())
    }

    // bytes suffix = 3;


    pub fn get_suffix(&self) -> &[u8] {
        &self.suffix
    }
    pub fn clear_suffix(&mut self) {
        self.suffix.clear();
    }

    // Param is passed by value, moved
    pub fn set_suffix(&mut self, v: ::std::vec::Vec<u8>) {
        self.suffix = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_suffix(&mut self) -> &mut ::std::vec::Vec<u8> {
        &mut self.suffix
    }

    // Take field
    pub fn take_suffix(&mut self) -> ::std::vec::Vec<u8> {
        ::std::mem::replace(&mut self.suffix, ::std::vec::Vec::new())
    }
}

impl ::protobuf::Message for InnerOp {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_proto3_enum_with_unknown_fields_into(wire_type, is, &mut self.hash, 1, &mut self.unknown_fields)?
                },
                2 => {
                    ::protobuf::rt::read_singular_proto3_bytes_into(wire_type, is, &mut self.prefix)?;
                },
                3 => {
                    ::protobuf::rt::read_singular_proto3_bytes_into(wire_type, is, &mut self.suffix)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if self.hash != HashOp::NO_HASH {
            my_size += ::protobuf::rt::enum_size(1, self.hash);
        }
        if !self.prefix.is_empty() {
            my_size += ::protobuf::rt::bytes_size(2, &self.prefix);
        }
        if !self.suffix.is_empty() {
            my_size += ::protobuf::rt::bytes_size(3, &self.suffix);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if self.hash != HashOp::NO_HASH {
            os.write_enum(1, self.hash.value())?;
        }
        if !self.prefix.is_empty() {
            os.write_bytes(2, &self.prefix)?;
        }
        if !self.suffix.is_empty() {
            os.write_bytes(3, &self.suffix)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> InnerOp {
        InnerOp::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeEnum<HashOp>>(
                    "hash",
                    |m: &InnerOp| { &m.hash },
                    |m: &mut InnerOp| { &mut m.hash },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeBytes>(
                    "prefix",
                    |m: &InnerOp| { &m.prefix },
                    |m: &mut InnerOp| { &mut m.prefix },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeBytes>(
                    "suffix",
                    |m: &InnerOp| { &m.suffix },
                    |m: &mut InnerOp| { &mut m.suffix },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<InnerOp>(
                    "InnerOp",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static InnerOp {
        static mut instance: ::protobuf::lazy::Lazy<InnerOp> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const InnerOp,
        };
        unsafe {
            instance.get(InnerOp::new)
        }
    }
}

impl ::protobuf::Clear for InnerOp {
    fn clear(&mut self) {
        self.hash = HashOp::NO_HASH;
        self.prefix.clear();
        self.suffix.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for InnerOp {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for InnerOp {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct ProofSpec {
    // message fields
    pub leaf_spec: ::protobuf::SingularPtrField<LeafOp>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a ProofSpec {
    fn default() -> &'a ProofSpec {
        <ProofSpec as ::protobuf::Message>::default_instance()
    }
}

impl ProofSpec {
    pub fn new() -> ProofSpec {
        ::std::default::Default::default()
    }

    // .proofs.LeafOp leaf_spec = 1;


    pub fn get_leaf_spec(&self) -> &LeafOp {
        self.leaf_spec.as_ref().unwrap_or_else(|| LeafOp::default_instance())
    }
    pub fn clear_leaf_spec(&mut self) {
        self.leaf_spec.clear();
    }

    pub fn has_leaf_spec(&self) -> bool {
        self.leaf_spec.is_some()
    }

    // Param is passed by value, moved
    pub fn set_leaf_spec(&mut self, v: LeafOp) {
        self.leaf_spec = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_leaf_spec(&mut self) -> &mut LeafOp {
        if self.leaf_spec.is_none() {
            self.leaf_spec.set_default();
        }
        self.leaf_spec.as_mut().unwrap()
    }

    // Take field
    pub fn take_leaf_spec(&mut self) -> LeafOp {
        self.leaf_spec.take().unwrap_or_else(|| LeafOp::new())
    }
}

impl ::protobuf::Message for ProofSpec {
    fn is_initialized(&self) -> bool {
        for v in &self.leaf_spec {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.leaf_spec)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let Some(ref v) = self.leaf_spec.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if let Some(ref v) = self.leaf_spec.as_ref() {
            os.write_tag(1, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> ProofSpec {
        ProofSpec::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<LeafOp>>(
                    "leaf_spec",
                    |m: &ProofSpec| { &m.leaf_spec },
                    |m: &mut ProofSpec| { &mut m.leaf_spec },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<ProofSpec>(
                    "ProofSpec",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static ProofSpec {
        static mut instance: ::protobuf::lazy::Lazy<ProofSpec> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ProofSpec,
        };
        unsafe {
            instance.get(ProofSpec::new)
        }
    }
}

impl ::protobuf::Clear for ProofSpec {
    fn clear(&mut self) {
        self.leaf_spec.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for ProofSpec {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ProofSpec {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(Clone,PartialEq,Eq,Debug,Hash)]
pub enum HashOp {
    NO_HASH = 0,
    SHA256 = 1,
    SHA512 = 2,
    KECCAK = 3,
    RIPEMD160 = 4,
    BITCOIN = 5,
}

impl ::protobuf::ProtobufEnum for HashOp {
    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<HashOp> {
        match value {
            0 => ::std::option::Option::Some(HashOp::NO_HASH),
            1 => ::std::option::Option::Some(HashOp::SHA256),
            2 => ::std::option::Option::Some(HashOp::SHA512),
            3 => ::std::option::Option::Some(HashOp::KECCAK),
            4 => ::std::option::Option::Some(HashOp::RIPEMD160),
            5 => ::std::option::Option::Some(HashOp::BITCOIN),
            _ => ::std::option::Option::None
        }
    }

    fn values() -> &'static [Self] {
        static values: &'static [HashOp] = &[
            HashOp::NO_HASH,
            HashOp::SHA256,
            HashOp::SHA512,
            HashOp::KECCAK,
            HashOp::RIPEMD160,
            HashOp::BITCOIN,
        ];
        values
    }

    fn enum_descriptor_static() -> &'static ::protobuf::reflect::EnumDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::EnumDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                ::protobuf::reflect::EnumDescriptor::new("HashOp", file_descriptor_proto())
            })
        }
    }
}

impl ::std::marker::Copy for HashOp {
}

impl ::std::default::Default for HashOp {
    fn default() -> Self {
        HashOp::NO_HASH
    }
}

impl ::protobuf::reflect::ProtobufValue for HashOp {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Enum(self.descriptor())
    }
}

#[derive(Clone,PartialEq,Eq,Debug,Hash)]
pub enum LengthOp {
    NO_PREFIX = 0,
    VAR_PROTO = 1,
    VAR_RLP = 2,
    FIXED32_BIG = 3,
    FIXED32_LITTLE = 4,
    FIXED64_BIG = 5,
    FIXED64_LITTLE = 6,
    REQUIRE_32_BYTES = 7,
    REQUIRE_64_BYTES = 8,
}

impl ::protobuf::ProtobufEnum for LengthOp {
    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<LengthOp> {
        match value {
            0 => ::std::option::Option::Some(LengthOp::NO_PREFIX),
            1 => ::std::option::Option::Some(LengthOp::VAR_PROTO),
            2 => ::std::option::Option::Some(LengthOp::VAR_RLP),
            3 => ::std::option::Option::Some(LengthOp::FIXED32_BIG),
            4 => ::std::option::Option::Some(LengthOp::FIXED32_LITTLE),
            5 => ::std::option::Option::Some(LengthOp::FIXED64_BIG),
            6 => ::std::option::Option::Some(LengthOp::FIXED64_LITTLE),
            7 => ::std::option::Option::Some(LengthOp::REQUIRE_32_BYTES),
            8 => ::std::option::Option::Some(LengthOp::REQUIRE_64_BYTES),
            _ => ::std::option::Option::None
        }
    }

    fn values() -> &'static [Self] {
        static values: &'static [LengthOp] = &[
            LengthOp::NO_PREFIX,
            LengthOp::VAR_PROTO,
            LengthOp::VAR_RLP,
            LengthOp::FIXED32_BIG,
            LengthOp::FIXED32_LITTLE,
            LengthOp::FIXED64_BIG,
            LengthOp::FIXED64_LITTLE,
            LengthOp::REQUIRE_32_BYTES,
            LengthOp::REQUIRE_64_BYTES,
        ];
        values
    }

    fn enum_descriptor_static() -> &'static ::protobuf::reflect::EnumDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::EnumDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                ::protobuf::reflect::EnumDescriptor::new("LengthOp", file_descriptor_proto())
            })
        }
    }
}

impl ::std::marker::Copy for LengthOp {
}

impl ::std::default::Default for LengthOp {
    fn default() -> Self {
        LengthOp::NO_PREFIX
    }
}

impl ::protobuf::reflect::ProtobufValue for LengthOp {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Enum(self.descriptor())
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x0cproofs.proto\x12\x06proofs\"\x81\x01\n\x0eExistenceProof\x12\x10\n\
    \x03key\x18\x01\x20\x01(\x0cR\x03key\x12\x14\n\x05value\x18\x02\x20\x01(\
    \x0cR\x05value\x12\"\n\x04leaf\x18\x03\x20\x01(\x0b2\x0e.proofs.LeafOpR\
    \x04leaf\x12#\n\x04path\x18\x04\x20\x03(\x0b2\x0f.proofs.InnerOpR\x04pat\
    h\"\xd4\x01\n\x06LeafOp\x12\"\n\x04hash\x18\x01\x20\x01(\x0e2\x0e.proofs\
    .HashOpR\x04hash\x12/\n\x0bprehash_key\x18\x02\x20\x01(\x0e2\x0e.proofs.\
    HashOpR\nprehashKey\x123\n\rprehash_value\x18\x03\x20\x01(\x0e2\x0e.proo\
    fs.HashOpR\x0cprehashValue\x12(\n\x06length\x18\x04\x20\x01(\x0e2\x10.pr\
    oofs.LengthOpR\x06length\x12\x16\n\x06prefix\x18\x05\x20\x01(\x0cR\x06pr\
    efix\"]\n\x07InnerOp\x12\"\n\x04hash\x18\x01\x20\x01(\x0e2\x0e.proofs.Ha\
    shOpR\x04hash\x12\x16\n\x06prefix\x18\x02\x20\x01(\x0cR\x06prefix\x12\
    \x16\n\x06suffix\x18\x03\x20\x01(\x0cR\x06suffix\"8\n\tProofSpec\x12+\n\
    \tleaf_spec\x18\x01\x20\x01(\x0b2\x0e.proofs.LeafOpR\x08leafSpec*U\n\x06\
    HashOp\x12\x0b\n\x07NO_HASH\x10\0\x12\n\n\x06SHA256\x10\x01\x12\n\n\x06S\
    HA512\x10\x02\x12\n\n\x06KECCAK\x10\x03\x12\r\n\tRIPEMD160\x10\x04\x12\
    \x0b\n\x07BITCOIN\x10\x05*\xab\x01\n\x08LengthOp\x12\r\n\tNO_PREFIX\x10\
    \0\x12\r\n\tVAR_PROTO\x10\x01\x12\x0b\n\x07VAR_RLP\x10\x02\x12\x0f\n\x0b\
    FIXED32_BIG\x10\x03\x12\x12\n\x0eFIXED32_LITTLE\x10\x04\x12\x0f\n\x0bFIX\
    ED64_BIG\x10\x05\x12\x12\n\x0eFIXED64_LITTLE\x10\x06\x12\x14\n\x10REQUIR\
    E_32_BYTES\x10\x07\x12\x14\n\x10REQUIRE_64_BYTES\x10\x08b\x06proto3\
";

static mut file_descriptor_proto_lazy: ::protobuf::lazy::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::lazy::Lazy {
    lock: ::protobuf::lazy::ONCE_INIT,
    ptr: 0 as *const ::protobuf::descriptor::FileDescriptorProto,
};

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    unsafe {
        file_descriptor_proto_lazy.get(|| {
            parse_descriptor_proto()
        })
    }
}
