name: Tests 
on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}-tests
  cancel-in-progress: true

jobs:
  go-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19.2
      - name: test
        run: |
          cd go && make test

  ts-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test
        run: |
          cd js && yarn && yarn test

  rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cd rust
      - name: Check all target in std
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all
      - name: Check all target in no_std    
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --no-default-features --all
      - name: Build all targets in std   
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all --all-targets
      - name: Build all targets in no_std    
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all --no-default-features
      - name: Run all tests with no-std
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all --no-default-features
      - name: Run all tests with std
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all 
      - name: check no_std compatibility
        run: cd no-std-check/; make setup; make all

        
